// ── Category definitions matching the backend default_categories.json ──
export const CATEGORY_OPTIONS = [
  {
    value: "uncategorized",
    label: "Uncategorized",
    icon: "question-circle",
    color: "#BDC3C7",
    parent: null,
  },
  {
    value: "food_dining",
    label: "Food and Dining",
    icon: "utensils",
    color: "#E67E22",
    parent: "expenses",
  },
  {
    value: "groceries",
    label: "Groceries",
    icon: "shopping-basket",
    color: "#27AE60",
    parent: "expenses",
  },
  {
    value: "shopping",
    label: "Shopping",
    icon: "shopping-bag",
    color: "#8E44AD",
    parent: "expenses",
  },
  {
    value: "transport",
    label: "Transport",
    icon: "car",
    color: "#2980B9",
    parent: "expenses",
  },
  {
    value: "utilities",
    label: "Utilities",
    icon: "bolt",
    color: "#16A085",
    parent: "expenses",
  },
  {
    value: "utility_bills",
    label: "Utility Bills",
    icon: "file-text",
    color: "#1ABC9C",
    parent: "expenses",
  },
  {
    value: "income_salary",
    label: "Salary",
    icon: "briefcase",
    color: "#2ECC71",
    parent: "income",
  },
  {
    value: "personal_transfer",
    label: "Personal Transfer",
    icon: "exchange",
    color: "#7F8C8D",
    parent: "transfer",
  },
  {
    value: "apps_and_software",
    label: "Apps and Software",
    icon: "monitor",
    color: "#3498DB",
    parent: "expenses",
  },
  {
    value: "banking_and_finance",
    label: "Banking and Finance",
    icon: "landmark",
    color: "#2C3E50",
    parent: "finance",
  },
  {
    value: "cards_and_finance_charges",
    label: "Cards and Finance Charges",
    icon: "credit-card",
    color: "#34495E",
    parent: "finance",
  },
  {
    value: "education",
    label: "Education",
    icon: "graduation-cap",
    color: "#9B59B6",
    parent: "expenses",
  },
  {
    value: "emi",
    label: "EMI",
    icon: "calendar",
    color: "#E74C3C",
    parent: "finance",
  },
  {
    value: "entertainment",
    label: "Entertainment",
    icon: "film",
    color: "#E91E63",
    parent: "expenses",
  },
  {
    value: "medical",
    label: "Medical",
    icon: "heart-pulse",
    color: "#E74C3C",
    parent: "expenses",
  },
  {
    value: "health_and_wellness",
    label: "Health and Wellness",
    icon: "activity",
    color: "#1ABC9C",
    parent: "expenses",
  },
  {
    value: "wallet_and_digital_payment",
    label: "Wallet and Digital Payment",
    icon: "wallet",
    color: "#F39C12",
    parent: "transfer",
  },
  {
    value: "cash_withdrawal",
    label: "Cash Withdrawal",
    icon: "banknote",
    color: "#95A5A6",
    parent: "transfer",
  },
  {
    value: "reversal_and_refunds",
    label: "Reversal and Refunds",
    icon: "undo",
    color: "#2ECC71",
    parent: "income",
  },
  {
    value: "rent",
    label: "Rent",
    icon: "home",
    color: "#D35400",
    parent: "expenses",
  },
  {
    value: "cars_and_rentals",
    label: "Cars and Rentals",
    icon: "car",
    color: "#2980B9",
    parent: "expenses",
  },
  {
    value: "government_payments",
    label: "Government Payments",
    icon: "landmark",
    color: "#7F8C8D",
    parent: "expenses",
  },
  {
    value: "insurance",
    label: "Insurance",
    icon: "shield",
    color: "#1F618D",
    parent: "finance",
  },
  {
    value: "wallet_loads",
    label: "Wallet Loads",
    icon: "wallet",
    color: "#F1C40F",
    parent: "transfer",
  },
  {
    value: "professional_services",
    label: "Professional Services",
    icon: "briefcase",
    color: "#8E44AD",
    parent: "expenses",
  },
  {
    value: "credit_card_bills",
    label: "Credit Card Bills",
    icon: "credit-card",
    color: "#C0392B",
    parent: "finance",
  },
  {
    value: "cashback",
    label: "Cashback",
    icon: "gift",
    color: "#27AE60",
    parent: "income",
  },
  {
    value: "friends",
    label: "Friends",
    icon: "users",
    color: "#3498DB",
    parent: "transfer",
  },
  {
    value: "others",
    label: "Others",
    icon: "more-horizontal",
    color: "#95A5A6",
    parent: null,
  },
  // investments
  {
    value: "investments",
    label: "Investments",
    icon: "chart-line",
    color: "#2C3E50",
    parent: "finance",
  },
] as const;
